 # Python 在計算上的優勢
 
 Python 與 C 語言的相容性以及轉換效率別高，因此在做多重數據計算時候，相較於Javascript效率會更好。而 Numpy 的這個應用庫則是Python的殺手級應用，在數據統計上有著相當傑出的表現。
 
 目前我們需要知道的數學概念包括一維的數組，如同`[1, 2, 3]`，或者像是二維數組matrix `[[1, 2, 3], [4, 5, 6]]`。而三維 tensor 則較不直觀。因此，我們先從一維與二維開始，三維以後則從數學上推演即可。

In [4]:
import numpy as np

如果我們要創建數組怎麼做呢?

In [18]:
x = np.array([1.0, 2.0, 3.0])

In [5]:
print(x)
print(x[0], x[1], x[2])
print(type(x))

[1. 2. 3.]
1.0 2.0 3.0
<class 'numpy.ndarray'>


第一個`[1. 2. 3.]`代表著這組數組裏頭的數字是浮點數 `float`，而後投若是 0則會被省略。

In [6]:
print(np.ndim(x))
print(x.ndim)
print(x.shape)
print(x.shape[0]) #這個數組的形狀，意思是在每一個維度上有幾個元素
print(x.dtype) # dtype指的是 data type，意味著裏頭裝的是什麼數據

1
1
(3,)
3
float64


注意，雖然烈表示可以放不同的數據類型，但是numpy裏頭的數組必須是同樣的數據類型

In [8]:
x1 = x.astype(np.float32) # 將 data type 改換，而這部分的範例是把精度從 64下降到 32，增加效能
print(x1)
print(x1.dtype)

[1. 2. 3.]
float32


In [9]:
x2 = np.array([1, 2, 3], dtype=np.float32)
print(x2)
print(x2.dtype)

[1. 2. 3.]
float32


向量也是可以做運算的，比如:

In [11]:
y = np.array([2.0, 4.0, 6.0])
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


上面的例子還可以寫成如下形式:

In [16]:
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


以下為用 Latex語法寫成的數學表達式，記得要用mardown執行，否則會報錯。

$$x = \begin{pmatrix} a_{1} & a_{2} & a_{3} \end{pmatrix}$$

$$y = \begin{pmatrix} b_{1} & b_{2} & b_{3} \end{pmatrix}$$

$$x \cdot y = a_{1}b_{1} + a_{2}b_{2} + a_{3}b{3}$$

上面寫法如下:

`$$x = \begin{pmatrix} a_{1} & a_{2} & a_{3} \end{pmatrix}$$`

`$$y = \begin{pmatrix} b_{1} & b_{2} & b_{3} \end{pmatrix}$$`

`$$x \cdot y = a_{1}b_{1} + a_{2}b_{2} + a_{3}b{3}$$`

而這樣算出來的不是向量，而是標量，得出的是一個數，也可以在python裏頭用以下方式計算

In [22]:
print(x.dot(y)) # 點集
print(np.dot(x, y))

28.0
28.0


In [24]:
print(x/ 2.0) # procasting 功能

[0.5 1.  1.5]


下面與上面等價，只是寫法較複雜，因此用 procasting其實方便許多。

In [26]:
print(x / np.array([2.0, 2.0, 2.0])) 

[0.5 1.  1.5]


## 二維數組的玩法

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [29]:
print(A.ndim)
print(A.shape)
print(A.shape[0]) # 想知道第一個維度有幾個數
print(A.dtype)
print(A[1])
print(A[1][0])

2
(2, 3)
2
int32
[4 5 6]
4


這個數組也算是個容器，因此可以取出其中的元素

In [30]:
for row in A:
    print(row)

[1 2 3]
[4 5 6]


## 二維數組的運算
接下來如同一維中的介紹，我們來看對二維的數組運算操作示範

In [5]:
B = np.array([[0.1, 0.2, 0.3], [0.1, 0.2, 0.3]])

In [33]:
print(A + B)
print(np.add(A, B))

[[1.1 2.2 3.3]
 [4.1 5.2 6.3]]
[[1.1 2.2 3.3]
 [4.1 5.2 6.3]]


In [35]:
print(A * B)
print(np.multiply(A, B))

[[0.1 0.4 0.9]
 [0.4 1.  1.8]]
[[0.1 0.4 0.9]
 [0.4 1.  1.8]]


In [36]:
print(A * 10) # 也可以做矩陣與標量的處理

[[10 20 30]
 [40 50 60]]


In [37]:
print(A * np.full((2, 3), 10)) # np.full是快速幫助我們創建一個數組，裏頭所有元素都是 10

[[10 20 30]
 [40 50 60]]


另外，我們來看一個數學公式:
$$A = \begin{pmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \end{pmatrix} = \begin{pmatrix} \vec{a_{1}} \\ \vec{a_{2}} \end{pmatrix}$$

$$B = \begin{pmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \\ b_{31} & b_{32} \end{pmatrix} = \begin{pmatrix} \vec{b_{1}} & \vec{b_{2}} \end{pmatrix}$$

$$A \cdot B = \begin{pmatrix} \vec{a_{1}} \cdot \vec{b_{1}} & \vec{a_{1}} \cdot \vec{b_{2}} \\ \vec{a_{2}} \cdot \vec{b_{1}} & \vec{a_{2}} \cdot \vec{b_{2}} \end{pmatrix} = \begin{pmatrix} a_{11}b_{11}+a_{12}b_{21}+a_{13}b_{31} & a_{11}b_{12}+a_{12}b_{22}+a_{13}b_{32} \\
a_{21}b_{11}+a_{22}b_{21}+a_{23}b_{31} & a_{21}b_{12}+a_{22}b_{22}+a_{23}b_{32} \end{pmatrix}$$

In [38]:
print(A)
print(B)
print(B.T) #B.transpose 縮寫 (轉置矩陣)，沿著主對角線做翻轉

[[1 2 3]
 [4 5 6]]
[[0.1 0.2 0.3]
 [0.1 0.2 0.3]]
[[0.1 0.1]
 [0.2 0.2]
 [0.3 0.3]]


In [41]:
# print(A.dot(B)) 會報錯
print(A.dot(B.T))
print(np.dot(A, B.T))

[[1.4 1.4]
 [3.2 3.2]]
[[1.4 1.4]
 [3.2 3.2]]


In [42]:
print(np.dot(B.T, A))

[[0.5 0.7 0.9]
 [1.  1.4 1.8]
 [1.5 2.1 2.7]]


位置交換之後，兩者的差異，顯示出沒有交換律，需要特別注意!

另外，在神經網絡中，每一層都是得到一個向量矩陣，因此對於此矩陣的理解相當重要。

In [4]:
v = np.array([0.1, 0.2, 0.3])
w = np.array([1 ,4])

In [44]:
print(A.dot(v)) 

[1.4 3.2]


之所以沒有報錯，是因為一維的數列在 numpy上可以自動轉換。真實的數學橫的寫跟豎著寫是不一樣的。

In [45]:
print(v.dot(B.T))

[0.14 0.14]


In [46]:
print(B.T.dot(w))

[0.5 1.  1.5]


目前為止我們講了 numpy的向量與操作，需要複習的部分包含線性代數的矩陣內容。

In [8]:
a = np.zeros((3, 3)) # 創建一個 3X3 裏頭數字都為 0的數組
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
b = np.ones((1, 4))
print(b)

[[1. 1. 1. 1.]]


In [11]:
c = np.full((3, 3), 7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [12]:
d = np.eye(4) # 主對角線為 1，原本應該是大寫的 I，這裡用諧音
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
e = np.random.random((3, 4))
print(e)

[[0.32108041 0.99191443 0.60593106 0.00149422]
 [0.99269627 0.11483181 0.74663972 0.36987745]
 [0.27941102 0.17297901 0.06397045 0.84346934]]


In [16]:
f = np.arange(0, 1, 0.2) # 創建向量的辦法，前面兩個參數表示數值範圍，最後一個是間隔多少
print(f)

[0.  0.2 0.4 0.6 0.8]


In [19]:
print(np.sin(x))
print(np.sqrt(A))

[0.84147098 0.90929743 0.14112001]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [20]:
print(A)
print(np.sum(A))
print(np.sum(A, axis=0))
print(np.sum(A, axis=1)) # 行 與 列向量也會寫成橫寫的格式

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]


前面的操作除了點集與 transferse指令外，不會改變數組的shape

In [22]:
print(B)
C = B.flatten() # 拍平，降維打擊:D
print(C)

[[0.1 0.2 0.3]
 [0.1 0.2 0.3]]
[0.1 0.2 0.3 0.1 0.2 0.3]


In [23]:
p = np.arange(0, 1, 0.1)
print(p)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [24]:
p = p.reshape((5, 2)) # 形狀的參數類型是 tuple；reshape必須符合原本數組的元素數量
print(p)

[[0.  0.1]
 [0.2 0.3]
 [0.4 0.5]
 [0.6 0.7]
 [0.8 0.9]]


In [25]:
q = np.arange(1, 2, 0.1).reshape((5, 2))
print(q)

[[1.  1.1]
 [1.2 1.3]
 [1.4 1.5]
 [1.6 1.7]
 [1.8 1.9]]


In [26]:
print(np.concatenate((p, q), axis=1))

[[0.  0.1 1.  1.1]
 [0.2 0.3 1.2 1.3]
 [0.4 0.5 1.4 1.5]
 [0.6 0.7 1.6 1.7]
 [0.8 0.9 1.8 1.9]]


In [27]:
print(C)

[0.1 0.2 0.3 0.1 0.2 0.3]


In [28]:
C > 0.15 # 產生了新的數組，變成了布爾向量。

array([False,  True,  True, False,  True,  True])

In [29]:
C[[False,  True,  True, False,  True,  True]]

array([0.2, 0.3, 0.2, 0.3])

In [30]:
C[C > 0.15] # 把上面兩部結合起來。

array([0.2, 0.3, 0.2, 0.3])

In [31]:
C[C > 0.15] -= 0.15
print(C)

[0.1  0.05 0.15 0.1  0.05 0.15]


In [62]:
D = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(D)
print(D.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [63]:
D1 = D[0:2, 1:3] # 做切片，從頭開始切，前面指定要切的列數，後面指定要切的行數，在此與D[0:2, 1:3]等效。
print(D1)
print(D1.shape)

[[2 3]
 [6 7]]
(2, 2)


在這裡對於切片的理解有些卡關，在經過反覆聽這一片斷後的測試如下:

In [64]:
D2 = D[2:3, 0:3]
print(D2)
type(D2)

[[ 9 10 11]]


numpy.ndarray

得到的結論就是，這種切片法前面的位置參數指定的是列數，後面的指定的是行數。不過有一點要注意，當我用`D[2, 0:3]`得到的輸出會是`[9 10 11]`，而用`D[2:3, 0:3]`得到的輸出會是`[[9 10 11]]`，用type查詢得到的都是`numpy.ndarray`，暫時不知道有什麼區別。下面的筆記與內容有提到，差異在於指定範圍的用`.shape`查詢下不會有降維的狀況發生；反之只有指定某一列的動作，會讓這裡的輸出變成只有一維(參見更下方的示例)。

注意! 對切片裡做動作也會改變原本的數組內容，這一點跟 list不同。

In [65]:
D1[0, 0] = 42
print(D1)
print(D)

[[42  3]
 [ 6  7]]
[[ 1 42  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


指定某列與指定範圍的差異:

In [66]:
r1 = D[1, :]
r2 = D[1:2, :]
print(r1, r1.shape)
print(r2, r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


指定某行與指定範圍的差異，與上方範例雷同:

In [69]:
t1 = D[:, 2]
t2 = D[:, 2:3]
print(t1, t1.shape)
print(t2, t2.shape)

[ 3  7 11] (3,)
[[ 3]
 [ 7]
 [11]] (3, 1)


## 下標數組

有些時候我們會需要挑出零散的數據，再做處理成一個新的向量的話，我們能怎麼做呢?

In [70]:
print(D)

[[ 1 42  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [71]:
print(D[0][0], D[0][1], D[1][0], D[2][3])
print(D[0, 0], D[0, 1], D[1, 0], D[2, 3]) # 與上面等價

1 42 5 12
1 42 5 12


In [74]:
print(np.array([D[0, 0], D[0, 1], D[1, 0], D[2, 3]]))

[ 1 42  5 12]


In [78]:
print(D[[0, 0, 1, 2], [0, 1, 0, 3]]) # 上方的簡潔寫法

[ 1 42  5 12]


In [81]:
print(D[2, 2]) # 從座標中指定要哪個數

11


## 再談Broadcasting

In [82]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
u = np.array([1, 0, 1])
Y = np.empty_like(X)

for i in range(4):
    Y[i, :] = X[i, :] + u
    
print(Y)

# 假設我們想把數組中的每一個都加上一個向量，我們可以怎麼做?

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [85]:
# 還可以用另外更簡單的方法來做

U = np.tile(u, [4, 1])
print(U)
Y = X + u
print(Y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [87]:
print(X + u) # 其實 numpy會自動擴充，做的是跟上面的一樣，這就稱為Broadcasting。

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


這裡李駿老師介紹了 Brodcasting的[官方網站](https://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc)文檔，講述著什麼情況下Broadcasting會怎麼做堆疊，什麼時候不會。凡是支持的稱為universal function，內容挺多，有空可以自行延伸閱讀。

最後，我們來做點腦筋體操，鍛鍊一下思維。
首先我們定義一下矩陣:

In [6]:
M = np.array([[1,2,3], [4,5,6]])
print(M)

[[1 2 3]
 [4 5 6]]


標量是 0維的

In [5]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5])

print(np.reshape(v1, (3, 1)) * v2)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [7]:
print(M + v1)

[[2 4 6]
 [5 7 9]]


In [9]:
print((M.T + v2).T)

[[ 5  6  7]
 [ 9 10 11]]


In [10]:
print(M + np.reshape(v2, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


從scipy 變成 numpy

In [14]:
points = np.array([[0, 1], [1, 0], [2, 0]])

from scipy.spatial.distance import pdist, squareform
D = pdist(points, 'euclidean')
print(squareform(D))

[[0.         1.41421356 2.23606798]
 [1.41421356 0.         1.        ]
 [2.23606798 1.         0.        ]]


In [13]:
#!pip install scipy

     ---------------------------------------- 34.1/34.1 MB 3.5 MB/s eta 0:00:00



[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip
